CREATE DATABASE FeedbackHub_EnterpriseService;

USE FeedbackHub_EnterpriseService;

CREATE TABLE ENTERPRISES(
	[ID] INT NOT NULL IDENTITY(1,1),
	[NAME] VARCHAR(100) NOT NULL,
	[CNPJ] VARCHAR(14) NOT NULL,
	[DESCRIPTION] VARCHAR(200),

	CONSTRAINT PK_ENTERPRISE PRIMARY KEY([ID])
);