IF NOT EXISTS (SELECT 1 FROM SYS.databases WHERE NAME = 'FeedbackHub_FeedbackService') 
	CREATE DATABASE FeedbackHub_FeedbackService;
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables where name = 'FEEDBACK')
	CREATE TABLE FEEDBACK(
		[ID] INT NOT NULL IDENTITY(1,1),
		[IDPRODUCT] INT NOT NULL,
		[GRADE] INT NOT NULL,

		CONSTRAINT PK_FEEDBACK PRIMARY KEY([ID])
	);