CREATE DATABASE FeedbackHub_ProductService;
GO

USE FeedbackHub_ProductService;
GO

CREATE TABLE PRODUCTS(
	[ID] INT NOT NULL IDENTITY(1,1),
	[NAME] VARCHAR(70) NOT NULL,
	[DESCRIPTION] VARCHAR(250),
	[IDENTERPRISE] INT NOT NULL,
	[ISACTIVE] BIT NOT NULL DEFAULT(0),

	CONSTRAINT PK_PRODUCT PRIMARY KEY([ID], [IDENTERPRISE])
);